
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Johannes.Lange\pythonscripts\tkinterdesigner\designs\hier\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("814x555")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 555,
    width = 814,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    407.0,
    277.0,
    image=image_image_1
)

canvas.create_text(
    269.0,
    15.0,
    anchor="nw",
    text="Automated Trading System",
    fill="#000000",
    font=("InriaSans Regular", 24 * -1)
)

canvas.create_rectangle(
    255.5,
    46.5,
    562.9999857953735,
    48.999999961013884,
    fill="#000000",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=622.0,
    y=489.0,
    width=178.0,
    height=58.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=589.0,
    y=144.0,
    width=201.0,
    height=71.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=48.0,
    y=79.0,
    width=178.0,
    height=58.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=48.0,
    y=79.0,
    width=178.0,
    height=58.0
)

canvas.create_text(
    99.0,
    171.0,
    anchor="nw",
    text=" ",
    fill="#000000",
    font=("InriaSans Regular", 14 * -1)
)

canvas.create_text(
    243.0,
    534.0,
    anchor="nw",
    text=" ",
    fill="#000000",
    font=("InriaSans Regular", 14 * -1)
)
window.resizable(False, False)
window.mainloop()
